#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <algorithm>
#include <queue>
#include <map>
#include <set>
#include <random>
#include <unordered_map>
#include <list>
#include <ctime>
#include <iterator>

using namespace std;

/**
 * @brief Creates a list (vector) of neighbours for a given site (vertex) and solution. The neighbours are generated by swapping the 
 * atom type given at the current site with one of its connected site (vertices). 
 * 
 * 
 * @param solution -- A vector containing the current solution 
 * @param site -- The current site we're swapping with its connected sites.
 * @param connected_vertices  -- A vector of integers where each integers identifies the identifier of the connected site. 
 * @return vector<vector<int>> -- The list of new neighbour solutions.
 */
vector<vector<int>> create_neighbours(vector<int> &solution, int site, vector<int> &connected_vertices)
{
    vector<vector<int>> neighbours;
    for (auto &connected_vertex : connected_vertices)
    {
        if (connected_vertex < site)
        {
            continue;
        }

        vector<int> neighbour(solution.size(), 0);
        copy(solution.begin(), solution.end(), neighbour.begin());
        int tmp = neighbour[site];
        neighbour[site] = neighbour[connected_vertex];
        neighbour[connected_vertex] = tmp;
        bool is_equal = equal(solution.begin(), solution.end(), neighbour.begin());
        if (!is_equal)
        {
            neighbours.push_back(neighbour);
        }
    }
    return neighbours;
}

/**
 * @brief Compute cost will go through each site and compute the cost it generates with its connected sites.
 * 
 * @param solution -- A list (vector) of integers describing the type of each site where the site id 
 * is defined by the index of the array.
 * @param cost_matrix -- A 2D list (vector<vector>), representing the cost in energy between sites. (H_ij)
 * @param graph -- An unordered_map<vector<int>> where the key represents the identifier of the graph 
 * and the value represents a list (vector) of integers where each integer is a connected site.
 * @return int -- A computed cost in energy for the given solution.
 */
int compute_cost(vector<int> &solution, vector<vector<int>> &cost_matrix, unordered_map<int, vector<int>> &graph)
{
    int total_cost = 0;
    for (auto &it : graph)
    {
        int vertex = it.first;
        vector<int> connected_vertices = it.second;
        for (auto connected_vertex : connected_vertices)
        {
            // Solution[INDEX] represents the type of the atom at site INDEX.
            // I.e.: solution[3] would return the type of the atom residing in site number 3.
            // We use the type of vertex and connected_vertex to compute the link cost (in energy). 
            total_cost += cost_matrix[solution[vertex]][solution[connected_vertex]];
        }
    };
    return total_cost;
}

/**
 * @brief Driver program for the resolution of the Atom assignment problem
 *  * 
 * @param argc 
 * @param argv 
 * @return int - Represents the exit code
 */
int main(int argc, char *argv[])
{

    if (argc == 1)
    {
        printf("Utilisation: tp.sh -e [chemin_vers_exemplaire]\n [-p]");
        return -1;
    }

    string file_path;
    string file_arg(argv[1]);

    if (file_arg == "-e" && argc >= 3)
    {
        file_path = argv[2];
    }
    else
    {
        printf("Fichier d'exemplaire non valide ou manquant...\n");
        return -1;
    }

    bool show_result(argv[3]);

    ifstream file(file_path);

    if (!file.is_open())
    {
        printf("Fichier non valide\n");
        return -1;
    }

    /* Parse input */
    // Get the list of sites, the type counts and the count for the number of edges. (Respectively: t, k, |A|)
    int site_count, type_count, edges_count;
    file >> site_count >> type_count >> edges_count;

    vector<int> type_counts;
    int count;

    // Get the count of atoms per type
    for (int i = 0; i < type_count; i++)
    {
        file >> count;
        type_counts.push_back(count);
    }

    // Initialize and fill a matrix containing the bond energies between each site.
    vector<vector<int>> cost_matrix(type_count, vector<int>(0));

    int energy;
    for (int i = 0; i < type_count; i++)
    {
        for (int j = 0; j < type_count; j++)
        {
            file >> energy;
            cost_matrix[i].push_back(energy);
        }
    }

    // Initialize, create and fill the graph with all the sites;
    int vertex_a, vertex_b;
    unordered_map<int, vector<int>> graph;
    for (int i = 0; i < edges_count; i++)
    {
        file >> vertex_a >> vertex_b;
        graph[vertex_a].push_back(vertex_b);
    }

    
    vector<int> best_solution;
    vector<int> all_types(type_count, 0);

    // Fill an initial solution by going through each available type procedurally.
    // Create a second vector to use as a type counter
    copy(type_counts.begin(), type_counts.end(), all_types.begin());
    for (int site = 0; site < site_count; site++)
    {
        for (int i = 0; i < type_count; i++)
        {
            if (all_types[i] > 0)
            {
                best_solution.push_back(i);
                all_types[i]--;
                break;
            }
        }
    }


    auto rng = std::default_random_engine{};
    
    // Randomize the procedurally generated solution
    shuffle(best_solution.begin(), best_solution.end(), rng);
    int best_cost = compute_cost(best_solution, cost_matrix, graph);
    bool changed = false;
    while (true)
    {
        for (auto &it : graph)
        {
            // Create neighbours based on the current site and the current solution.
            vector<vector<int>> neighbours = create_neighbours(best_solution, it.first, it.second);

            for (auto n : neighbours)
            {
                int cost = compute_cost(n, cost_matrix, graph);
                if (cost < best_cost)
                {
                    best_solution = n;
                    best_cost = cost;
                    changed = true;

                    if (show_result)
                    {
                        copy(best_solution.begin(), best_solution.end(), std::ostream_iterator<int>(std::cout, " "));
                        cout << endl;
                    }
                    else 
                    {
                        cout << best_cost << endl;
                    }
                }
            }
        }

        // If we did not manage to generate any better neighbours, or any neighbours at all, we shuffle the current solution and 
        // restart the search.
        if (!changed)
        {
            shuffle(best_solution.begin(), best_solution.end(), rng);
        }

        changed = false;
    }

    return 0;
}
