/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 7.0.2 */
package analyzer.ast;

public interface ParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTDECLARATION = 1;
  public int JJTBLOCK = 2;
  public int JJTSTMT = 3;
  public int JJTFORSTMT = 4;
  public int JJTIFSTMT = 5;
  public int JJTWHILESTMT = 6;
  public int JJTASSIGNSTMT = 7;
  public int JJTEXPR = 8;
  public int JJTBOOLEXPR = 9;
  public int JJTCOMPEXPR = 10;
  public int JJTADDEXPR = 11;
  public int JJTMULEXPR = 12;
  public int JJTUNAEXPR = 13;
  public int JJTNOTEXPR = 14;
  public int JJTGENVALUE = 15;
  public int JJTBOOLVALUE = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTINTVALUE = 18;


  public String[] jjtNodeName = {
    "Program",
    "Declaration",
    "Block",
    "Stmt",
    "ForStmt",
    "IfStmt",
    "WhileStmt",
    "AssignStmt",
    "Expr",
    "BoolExpr",
    "CompExpr",
    "AddExpr",
    "MulExpr",
    "UnaExpr",
    "NotExpr",
    "GenValue",
    "BoolValue",
    "Identifier",
    "IntValue",
  };
}
/* JavaCC - OriginalChecksum=9782bd04470804b5cd1d7c6c3c314582 (do not edit this line) */
